CREATE TABLE sleep_user (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE sleep_data (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL,
    user_id INT NOT NULL,
    date_of_sleep TIMESTAMP NOT NULL,
    time_in_bed BIGINT,
    time_in_bed_start TIMESTAMP NOT NULL,
    time_in_bed_end TIMESTAMP NOT NULL,
    feeling VARCHAR(20) NOT NULL,
    CONSTRAINT fk_sleep_data_sleep_user FOREIGN KEY (user_id) REFERENCES sleep_user(id)
);

INSERT INTO sleep_user (id, uuid, name)
VALUES (
    1,
    'b7e2a7a5-7f5e-42b9-8d93-36df4a7df5c3',
    'Test User'
);